### PR TITLE
Adds jbase as a dependency

### PR DESCRIPTION
**Pull request by brkattk**

### CODE REVIEW

**Comment by Morgul** [comment]
The project `jbase` is deprecated; it was renamed to `trivialdb`, which as you can see, is a dependency.

What, exactly, were you trying to solve?

**Comment by brkattk** [comment]
Strange. I was following the instructions for installing and running and was getting this error:

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'jbase'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/brkattk/Code/wiki/node_modules/tome/server/models.js:8:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by Morgul** [comment]
Ah, when I did the conversion I accidentally didn't commit the changes to _use_ trivialdb, instead. I can get those pushed once I get home from work tonight.

Alternatively, if you simply replace 'jbase' with 'trivialdb' where ever it occurs in the `server` folder, it should just work.

Sorry about that!

**Comment by brkattk** [comment]
Cool. No problem. I figured it was a simple oversight. :+1:

**Comment by Morgul** [comment]
@brkattk I've published a new version that basically just has that change. It seems to have fixed it for me, let me know if you have any more issues!

**Pull request closed without merging**
